In [1]:
#Numpy practice
import numpy as np

In [2]:
#numpy version
print(np.__version__)

1.18.5


In [8]:
#CREATING ARRAYS 
array=np.array([1,2,3,4])
print(array)
#type
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
#we can also convert tuple into numpy arrays like lists
array=np.array((1,2,3,4))

In [11]:
#creating 2d arrays
array2d=np.array([[1,2,3,4],[5,6,7,8]])
array2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
#creating 3d arrays
array3d=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
array3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [18]:
#ndim is used to display dimension of an array
print(array.ndim)
print(array2d.ndim)
print(array3d.ndim)

1
2
3


In [32]:
#ARRAY INDEXING
a1=np.array([1,2,3,4])
print(a1[0])
print(a1[3])
print(a1[0]+a1[3])

1
4
5


In [23]:
#Array Indexing for 2d arrays
a2d=np.array([[1,2,3,4],[5,6,7,8]])
# element on 2nd row(index 1)and 3rd column(index 2)
print(a2d[1,2])
# element on 1st row(index 1)and 2rd column(index 2)
print(a2d[0,1])
#addition of them
print(a2d[1,2]+a2d[0,1])


7
2
9


In [30]:
#negative indexing
print(a1[-1])
print(a1[-4])
print(a2d[-1,2]) #negative represents from backside starts from -1 and continues from back as -2,-3,-4....
print(a2d[-1,-2])

4
1
7
7


In [4]:
#SLICING
#We pass slice instead of index like this: [start:end].
a1=np.array([1,2,3,4,5,6,7,8])
#The result includes the start index, but excludes the end index.
print(a1[1:3])
print(a1[2:3])
print(a1[3:8])
#If we don't pass end its considered length of array in that dimension
print(a1[2:])
#If we don't pass start its considered 0
print(a1[:5])
#Negative slicing 
print(a1[-3:-1])
print(a1[-4:])
print(a1[:-2])


[2 3]
[3]
[4 5 6 7 8]
[3 4 5 6 7 8]
[1 2 3 4 5]
[6 7]
[5 6 7 8]
[1 2 3 4 5 6]


In [3]:
#We can also define the step, like this: [start:end:step].
print(a1[1:8:2])#will take 2 steps from start
#If we don't pass step its considered 1
print(a1[1:8:])
#if we dont provide start and stop they will consider as first and last
print(a1[::2])

[2 4 6 8]
[2 3 4 5 6 7 8]
[1 3 5 7]


In [ ]:
#Slicing 2d arrays 